image:
    file: .gitpod.Dockerfile

ports:
- name: yugabyted-ui
  port: 15433
  visibility: private
- name: master-ui
  port: 7000
  visibility: private
- name: tserver-ui
  port: 9000
  visibility: private
- name: java-web
  port: 8080
  visibility: private
