
image:
    file: .gitpod.Dockerfile

ports:
- name: yugabyted-ui
  port: 15433
  visibility: private
- name: master-ui
  port: 7000
  visibility: private
- name: tserver-ui
  port: 9000
  visibility: private
- name: java-web
  port: 8080
  visibility: private

vscode:
  extensions:
    - Dart-Code.dart-code
    - tamasfe.even-better-toml
    - ms-azuretools.vscode-docker
    - dbaeumer.vscode-eslint
    - Dart-Code.flutter
    - redhat.vscode-yaml
    - GitHub.vscode-pull-request-github
    - eamodio.gitlens
    - shd101wyy.markdown-preview-enhanced
    - DavidAnson.vscode-markdownlint
    - chrischinchilla.vale-vscode
    - Tyriar.sort-lines